name: Documentation

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

# Allow the job to push to the gh-pages branch
permissions:
  contents: write

jobs:
  docc:
    name: Generate and Deploy Documentation
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Select Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Deploy to GitHub Pages
        uses: apple/swift-docc-plugin@v1
        with:
          target: IdentityKit
          hosting-base-path: IdentityKit
